# Generated by Django 5.1 on 2024-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
