# Generated by Django 5.1 on 2024-09-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_productdb_alter_categorydb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Category_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorydb'),
        ),
    ]
