# Generated by Django 5.1 on 2024-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_productdb_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Category_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
