# Generated by Django 5.1 on 2024-09-09 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_alter_productdb_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
