# Generated by Django 5.1 on 2024-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_productdb_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('coming_soon', 'Coming Soon')], default='available', max_length=20),
        ),
    ]
