# Generated by Django 5.1 on 2024-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_productdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='is_deal_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
