# Generated by Django 5.1 on 2024-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_cartdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Wishlist Images')),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='Image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
