# Generated by Django 5.1 on 2024-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_wishlistdb_alter_cartdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Total_Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
